### ISSUE TITLE
frechet_l and frechet_r have been removed as of SciPy 1.6.0 

### ISSUE THREAD

**Issue by PedroCaldeira** [JupitersMight/DI2#1]
In SciPy 1.6.0 frechet_l and frechet_r distributions were removed as they were deprecated since release 1.0.. 

From my tests (using the scipy==1.6.1) the inclusion of these distributions in the list of distributions crashes the program.

Possible solution:
- Removal of frechet_l and frechet_r from the list of distributions used

References: 
- [SciPy 1.6.0 Release Notes - deprecated features](https://docs.scipy.org/doc/scipy/reference/release.1.6.0.html?highlight=frechet_r#deprecated-features)

**Comment by JupitersMight** [comment]
Thank you for the feedback and sorry for the delayed fix. The issue has now been resolved.
